### ISSUE TITLE
Modrinth 업로드 제안

### ISSUE THREAD

**Issue by craftingmod** [Korea-Minecraft-Forum/CocoaInput#1]
현재 CocoaInput이 Discontinue된 상황에서 라이센스를 지키고 A fork of cocoainput~~~ 하면서 Modrinth에 올리시면 CJK 유저들이 잘 쓸것 같아서 Modrinth 업로드도 제안해봅니다!

한마포/깃헙에서만 받기엔 접근성이 많이 떨어져요 ㅠㅠ

**Comment by LemonCaramel** [comment]
안녕하세요
한마포에서 관리되고 있는 이 fork는 현재 최소한의 유지보수만 이루어지고 있습니다.

2023년은 저의 개인 일정으로 인해 여가 시간이 많지 않습니다. 현재 CocoaInput이 아직까지도 수정되지 않은 여러 버그를 가지고 있는데, Modrinth에 업로드하게 된다면 제가 감당하기 힘들 정도로 일이 커질 것만 같습니다.

또한, 지금 CocoaInput에 적용된 문자 입력 방식이 최선의 방법이었는지는 모르겠지만 그렇다고 이상적인 방법은 아닌 것 같습니다. 2024년이 되어서도 여전히 원본 리포지토리의 활동이 없거나 대체제가 없다면 그때 프로젝트 리팩토링을 진행하고 업로드해 보도록 하겠습니다.

감사합니다.

**Comment by craftingmod** [comment]
넵 감사합니다 :)
