### ISSUE TITLE
Please, Author, Support Version 1.12.2

### ISSUE THREAD

**Issue by nitian11** [Korea-Minecraft-Forum/CocoaInput#2]
Version 1.12.2 is a mod-rich version that needs support under Mac ARM. Thank you.

**Comment by Preta-Crowz** [comment]
This is fork of CocoaInput and original is already support 1.12.2.
Checkout original one here: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cocoainput/files)

**Comment by LemonCaramel** [comment]
This fork has no plans to support Minecraft 1.12.2.
